// Code generated by "stringer -type=functionType"; DO NOT EDIT.

package parsing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FUNCTION-0]
	_ = x[METHOD-1]
}

const _functionType_name = "FUNCTIONMETHOD"

var _functionType_index = [...]uint8{0, 8, 14}

func (i functionType) String() string {
	if i < 0 || i >= functionType(len(_functionType_index)-1) {
		return "functionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _functionType_name[_functionType_index[i]:_functionType_index[i+1]]
}
